/**
 * Regenerates supabase/seed.sql from the canonical data files in /data
 * (data/catalog.json and data/site-settings.json).
 * Run with: node scripts/generate-seed.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { categories, products, testimonials, discountCodes } = JSON.parse(
  readFileSync(join(root, "data", "catalog.json"), "utf8"),
);
const settings = JSON.parse(readFileSync(join(root, "data", "site-settings.json"), "utf8"));

const q = (s) => (s == null ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const j = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

let sql = `-- Trike Nation — seed data. Run after all files in migrations/.
-- Generated by scripts/generate-seed.mjs — edit the files in /data and regenerate.

begin;

delete from public.order_items;
delete from public.orders;
delete from public.testimonials;
delete from public.products;
delete from public.categories;
delete from public.discount_codes;
delete from public.site_settings;

`;

sql += "insert into public.categories (slug, name, tagline, badge, count, image, sort_order) values\n";
sql += categories
  .map(
    (c, i) =>
      `  (${q(c.slug)}, ${q(c.name)}, ${q(c.tagline)}, ${c.badge ? q(c.badge) : "null"}, ${c.count}, ${q(c.image)}, ${i})`,
  )
  .join(",\n");
sql += ";\n\n";

sql +=
  "insert into public.products (slug, name, category_slug, price_cents, compare_at_cents, badges, blurb, description, engine_size, specs, box_contents, features, image, featured, in_stock) values\n";
sql += products
  .map(
    (p) =>
      `  (${q(p.slug)}, ${q(p.name)}, ${q(p.category)}, ${p.priceCents}, ${p.compareAtCents ?? "null"}, ${j(p.badges)}, ${q(p.blurb)}, ${q(p.description)}, ${q(p.engineSize)}, ${j(p.specs)}, ${j(p.boxContents)}, ${j(p.features)}, ${q(p.image)}, ${p.featured}, ${p.inStock})`,
  )
  .join(",\n");
sql += ";\n\n";

sql += "insert into public.testimonials (name, initials, role, quote, rating, sort_order) values\n";
sql += testimonials
  .map((t, i) => `  (${q(t.name)}, ${q(t.initials)}, ${q(t.role)}, ${q(t.quote)}, ${t.rating}, ${i})`)
  .join(",\n");
sql += ";\n\n";

sql += "insert into public.discount_codes (code, percent_off, active) values\n";
sql += Object.entries(discountCodes)
  .map(([code, pct]) => `  (${q(code)}, ${pct}, true)`)
  .join(",\n");
sql += ";\n\n";

sql += `insert into public.site_settings (id, hero, announcements, contact, social) values
  (1, ${j(settings.hero)}, ${j(settings.announcements)}, ${j(settings.contact)}, ${j(settings.social)});

commit;
`;

writeFileSync(join(root, "supabase", "seed.sql"), sql);
console.log(
  `Wrote supabase/seed.sql (${products.length} products, ${categories.length} categories, settings row)`,
);
